# Theme metadata
name = "Minimal"

# Is theme light or dark?
light = true

# Primary
primary = "#e5be00"

# Menu
menu_primary = "#fff"
menu_text = "#34495e"
menu_text_active = "#e5be00"
menu_title = "#2b2b2b"

# Home sections
home_section_odd = "rgb(255, 255, 255)"
home_section_even = "rgb(247, 247, 247)"
